// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwcnWD4nk6aRZ1Jgl6KtjDKN6eTOziMlg',
    appId: '1:885434568694:web:2b3d87042c9dd44c8e41d7',
    messagingSenderId: '885434568694',
    projectId: 'bikein-a57e5',
    authDomain: 'bikein-a57e5.firebaseapp.com',
    storageBucket: 'bikein-a57e5.appspot.com',
    measurementId: 'G-GJQMMN64HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyReZyfLRHc-wP25BxsvVoI8NRupL9FY',
    appId: '1:885434568694:android:597c8097bb4cc15a8e41d7',
    messagingSenderId: '885434568694',
    projectId: 'bikein-a57e5',
    storageBucket: 'bikein-a57e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuwYM6dTUKjOkZGV-1_nLMYY_rlu5eS0',
    appId: '1:885434568694:ios:ce3c18805822af738e41d7',
    messagingSenderId: '885434568694',
    projectId: 'bikein-a57e5',
    storageBucket: 'bikein-a57e5.appspot.com',
    iosBundleId: 'com.example.bikeIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuwYM6dTUKjOkZGV-1_nLMYY_rlu5eS0',
    appId: '1:885434568694:ios:350b1d1fca18a8208e41d7',
    messagingSenderId: '885434568694',
    projectId: 'bikein-a57e5',
    storageBucket: 'bikein-a57e5.appspot.com',
    iosBundleId: 'com.example.bikeIn.RunnerTests',
  );
}
